### PR TITLE
WIP - Make an installable package

### PR DESCRIPTION
**Pull request by johnidm**
#### Description:
- Include requirements.txt.
- Add `setup*.` files to build a package.
- Create a folder `simple_diarizer` to store source code.
- Create Github Workflow to publish the package.

#### How to test:
- Run command `pip install .`
- Outside project folder type `python` and `from simple_diarizer import diarizer`

#### Notes:
- Cannot use python 3.10.x yet 

#### Source code to test:
```
from simple_diarizer.utils import (convert_wavfile, download_youtube_wav)

from simple_diarizer.diarizer import Diarizer
import tempfile

YOUTUBE_ID = "HyKmkLEtQbs"

with tempfile.TemporaryDirectory() as outdir:
    yt_file = download_youtube_wav(YOUTUBE_ID, outdir)

    wav_file = convert_wavfile(yt_file, f"{outdir}/{YOUTUBE_ID}_converted.wav")

    print(f"wav file: {wav_file}")

    diar = Diarizer(
        embed_model='ecapa', # supported types: ['xvec', 'ecapa']
        cluster_method='sc', # supported types: ['ahc', 'sc']
        window=1.5, # size of window to extract embeddings (in seconds)
        period=0.75 # hop of window (in seconds)
    )

    NUM_SPEAKERS = 2

    segments = diar.diarize(wav_file, 
                            num_speakers=NUM_SPEAKERS,
                            outfile=f"{outdir}/{YOUTUBE_ID}.rttm")

    print(segments)     
```

### CODE REVIEW

**Comment by johnidm** [comment]
@cvqluu I create a work-in-progress pull requests

Feel free to make comments. Soon the package will be ready.

When possible if you can you can send me your email to fill the `setup.cfg` file

**Comment by johnidm** [comment]
@cvqluu can you give a permission to create and update workflow?

I'm trying to commit the CI code but I'm getting the error below.

```
! [remote rejected] feature/requirements -> feature/requirements (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/github-actions-publish.yml` without `workflow` scope)
```

**Comment by cvqluu** [comment]
I think I had to set up an initial workflow on the main branch to allow this.

Maybe try again?

**Comment by johnidm** [comment]
I tried and it didn't work. I'm doing this on the branch **feature/requirements**

**Comment by cvqluu** [comment]
Hmm okay let me take a look tomorrow. Sorry for the delay

**Comment by cvqluu** [comment]
From this twitter post it may be to do with your personal access token?:

https://twitter.com/stauffermatt/status/1350897260108935171?lang=en-GB

**Comment by johnidm** [comment]
@cvqluu very strange this problem, I solved it. I created a new personal access token and changed the repo url from SSH to HTTPS.

Thanks.

**Comment by johnidm** [comment]
@cvqluu when possible, you should create a repository secret called PYPI_API_TOKEN

This secret will be used to public the package on PyPi.

How to generate API Token on PYPi: Login on PyPi > Account Settings -> API tokens - Add API Token

Hot to add a secret on GitHub: Click on the tab Settings of Project -> Secret -> New Repository Secret. 

When you do that, I can test the package publishing

**Comment by cvqluu** [comment]
Hey thanks for the detailed instructions! I will do this tomorrow when I am being productive again 😅

**Comment by cvqluu** [comment]
@johnidm The pypi repository secret should be there now. Thanks again for this!

**Comment by johnidm** [comment]
@cvqluu the error below is happening when trying to publish the package 

```
Error during upload. Retry with the --verbose option for more details.
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.
```
This page can be help - https://pypi.org/help/#invalid-auth

May be something is wrong with token.

**Comment by cvqluu** [comment]
Hmm, I didn't create a test pypi token before. The repository secrets now look like this

image

**Comment by cvqluu** [comment]
image

The checks are failing because my secret apparently doesn't start with pypi-

This is strange as I just updated them and they definitely do start with pypi-

**Comment by cvqluu** [comment]
Looks like things are working! Let me know if there's anything else that still needs to be done. If not, looks good to go and will approve and merge it.

Thanks again for this!

**Comment by johnidm** [comment]
@cvqluu I'm doing tests with the package.

And I need to make a documentation section on README and Project Description on PyPi.

**Comment by johnidm** [comment]
@cvqluu I finished the task

Check the example using PyPi - https://colab.research.google.com/drive/1bx0oF0qWynnrhgdIvEzaVKjdpCmMjq_d?usp=sharing

PyPi repository - https://pypi.org/project/simple-diarizer/

Feel free to review the source code and merge to main.

**Review by cvqluu — APPROVED** [review]
Looks great, and thanks for the colab demo - works a charm!

**Pull request merged**
